name: Build and Test Pull Request

on:
  pull_request:
    branches:
      - '*'  # Trigger this on PRs targeting any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.18'  # Specify the Node.js version

    - name: Install dependencies
      run: |
        npm install

    - name: Run build
      run: |
        npm run build  # Run the build command

    - name: Check if build was successful
      if: failure()  # If the build fails, the PR will not be merged
      run: |
        echo "Build failed. Please fix the issues before merging."
        exit 1  # Exits with non-zero status if the build fails
